<?php

namespace PB\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
<<<<<<< HEAD
	
	public function myFindAll()
	{

    	$queryBuilder = $this->createQueryBuilder('a');
		$query = $queryBuilder->getQuery();
		$results = $query->getResult();
    	return $results;

  }
=======
>>>>>>> 19dbb4597b2bc3fda234bc3f121204f5d358bc05
}
